### ISSUE TITLE
msgID is wrong

### ISSUE THREAD

**Issue by LucasLzh** [starkillerOG/HA-motion-blinds#2]
time_str = time.strftime("%Y%d%m%H%M%S%f")[:-3]
%Y%m%d%H%M%S%f is right

**Comment by starkillerOG** [comment]
Thanks for mentioning!
I just fixed it in the upstream library: https://github.com/starkillerOG/motion-blinds

It will be in the next release.
However it did not inpact functionality, as long as each message ID is unique there are no problems.
